SELECT
    CUSTOMERS.NAME,
    RENTALS.RENTALS_DATE
FROM CUSTOMERS
INNER JOIN RENTALS ON CUSTOMERS.ID = RENTALS.ID_CUSTOMERS
WHERE RENTALS.RENTALS_DATE >= '2016-09-01'
AND RENTALS.RENTALS_DATE <= '2016-09-30'
